version: "3.8"
services:
  hongguo-dl:
    image: gybeyond/hongguo-dl:latest
    container_name: hongguo-dl
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_PASSWORD=你的密码
    volumes:
      - /volume1/GY/hongguo-downloads:/downloads
      - /usr/bin/ffmpeg:/usr/local/bin/ffmpeg:ro
