plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hongguo.dl'
    compileSdk 34

    defaultConfig {
        applicationId "com.hongguo.dl"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('../hongguo.keystore')
            storePassword 'hongguo1997'
            keyAlias 'hongguo'
            keyPassword 'hongguo1997'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
