plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hongguo.dl'
    compileSdk 34

    defaultConfig {
        applicationId "com.hongguo.dl"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    flavorDimensions "version"
    productFlavors {
        full {
            dimension "version"
            applicationId "com.hongguo.dl"
            resValue "string", "app_name", "红果下载器"
        }
        nas {
            dimension "version"
            applicationId "com.hongguo.dl.nas"
            resValue "string", "app_name", "红果下载器-NAS"
        }
    }

    signingConfigs {
        release {
            storeFile file('../hongguo.keystore')
            storePassword 'hongguo1997'
            keyAlias 'hongguo'
            keyPassword 'hongguo1997'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        doNotStrip '**/*.so'
    }
}

dependencies {
    implementation 'org.mp4parser:isoparser:1.9.41'
    implementation 'org.mp4parser:muxer:1.9.41'
}
